"""add_voice_profiles_draft_actions_learning_signals_contact_type_chips

Revision ID: f02b301eaf7d
Revises: 021_task_source_traceability
Create Date: 2026-03-18 18:44:50.124479
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f02b301eaf7d'
down_revision: Union[str, None] = '021_task_source_traceability'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('correction', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('profile_text', sa.Text(), nullable=False),
    sa.Column('exemplar_bank', sa.JSON(), nullable=False),
    sa.Column('message_pattern', sa.String(length=20), nullable=False),
    sa.Column('burst_count', sa.Integer(), nullable=False),
    sa.Column('delay_range', sa.JSON(), nullable=False),
    sa.Column('message_count_analyzed', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draft_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_reply_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('edit_before', sa.Text(), nullable=True),
    sa.Column('edit_after', sa.Text(), nullable=True),
    sa.Column('manual_reply_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_reply_id'], ['ai_replies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # --- Drop old operator tables (order matters: FK dependencies) ---
    # 1. Drop FK columns that reference operator_actions
    op.execute(sa.text("DROP INDEX IF EXISTS ix_ai_training_data_action_id"))
    op.drop_column('ai_training_data', 'action_id')
    op.drop_column('ai_training_data', 'context_snapshot_ref')
    op.execute(sa.text("DROP INDEX IF EXISTS ix_tasks_source_action_id"))
    try:
        op.drop_column('tasks', 'source_action_id')
        op.drop_column('tasks', 'source_evidence_ref')
    except Exception:
        pass
    # 2. Drop operator_events first (has FK to operator_actions)
    op.drop_index(op.f('ix_operator_events_event_type'), table_name='operator_events')
    op.drop_index(op.f('ix_operator_events_occurred_at'), table_name='operator_events')
    op.drop_index(op.f('ix_operator_events_workspace_id'), table_name='operator_events')
    op.drop_table('operator_events')
    # 3. Now drop operator_actions (no more FKs pointing to it)
    op.drop_index(op.f('ix_operator_actions_conversation_id'), table_name='operator_actions')
    op.drop_index(op.f('ix_operator_actions_created_at'), table_name='operator_actions')
    op.drop_index(op.f('ix_operator_actions_workspace_id'), table_name='operator_actions')
    op.drop_table('operator_actions')
    # 4. Drop metric_snapshots and pipeline_stages (no FK deps)
    op.drop_index(op.f('ix_metric_snapshots_metric_date'), table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_workspace_id'), table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    op.drop_index(op.f('ix_pipeline_stages_workspace_id'), table_name='pipeline_stages')
    op.drop_table('pipeline_stages')
    op.add_column('ai_replies', sa.Column('chips', sa.JSON(), nullable=True))
    op.add_column('ai_replies', sa.Column('split_messages', sa.JSON(), nullable=True))
    op.alter_column('ai_replies', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('ai_replies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_ai_replies_override_reason'), table_name='ai_replies')
    op.alter_column('ai_training_data', 'signal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'1'::double precision"))
    op.alter_column('ai_training_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ai_training_data.action_id and context_snapshot_ref already dropped above
    op.alter_column('business_knowledge', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'faq'::character varying"))
    op.alter_column('business_knowledge', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('business_knowledge', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('business_knowledge', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('business_knowledge', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_business_knowledge_embedding'), table_name='business_knowledge', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_business_knowledge_workspace_active'), table_name='business_knowledge')
    op.alter_column('catalog_item_images', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('catalog_items', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'UZS'::character varying"))
    op.alter_column('catalog_items', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('catalog_items', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('catalog_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('catalog_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_catalog_items_embedding'), table_name='catalog_items', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('conversations', 'pipeline_stage',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'new'::character varying"))
    op.alter_column('conversations', 'needs_attention',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('customer_journey_events', 'event_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('customer_journey_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_journey_events_conversation_id'), table_name='customer_journey_events')
    op.drop_index(op.f('ix_journey_events_workspace_customer'), table_name='customer_journey_events')
    op.add_column('customers', sa.Column('contact_type', sa.String(length=20), nullable=False, server_default='customer'))
    op.add_column('customers', sa.Column('classification_confidence', sa.Float(), nullable=True))
    op.add_column('customers', sa.Column('classification_corrected', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.alter_column('customers', 'language',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'uz'::character varying"))
    op.alter_column('customers', 'lifetime_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('message_insights', 'products_mentioned',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('message_insights', 'objections',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('message_insights', 'urgency',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('message_insights', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_message_insights_conversation_id'), table_name='message_insights')
    op.drop_index(op.f('ix_message_insights_workspace_id'), table_name='message_insights')
    op.alter_column('messages', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_orders_conversation_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_workspace_id'), table_name='orders')
    # tasks.source_action_id already dropped above
    op.add_column('workspaces', sa.Column('trust_mode', sa.String(length=20), nullable=False, server_default='draft'))
    op.alter_column('workspaces', 'subscription_tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'free'::character varying"))
    op.alter_column('workspaces', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('workspaces', 'telegram_connected',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('workspaces', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('workspaces', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('workspaces', 'classify_credits')
    op.drop_column('workspaces', 'surface_autonomy_modes')
    op.drop_column('workspaces', 'rollback_reason')
    op.drop_column('workspaces', 'rollback_triggered_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('rollback_triggered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('workspaces', sa.Column('rollback_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('workspaces', sa.Column('surface_autonomy_modes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('workspaces', sa.Column('classify_credits', sa.INTEGER(), server_default=sa.text('50'), autoincrement=False, nullable=False))
    op.alter_column('workspaces', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workspaces', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workspaces', 'telegram_connected',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('workspaces', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('workspaces', 'subscription_tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'free'::character varying"))
    op.drop_column('workspaces', 'trust_mode')
    op.add_column('tasks', sa.Column('source_evidence_ref', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('source_action_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_tasks_source_action_id_operator_actions'), 'tasks', 'operator_actions', ['source_action_id'], ['id'])
    op.create_index(op.f('ix_tasks_source_action_id'), 'tasks', ['source_action_id'], unique=False)
    op.create_index(op.f('ix_orders_workspace_id'), 'orders', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_conversation_id'), 'orders', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_message_insights_workspace_id'), 'message_insights', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_message_insights_conversation_id'), 'message_insights', ['conversation_id'], unique=False)
    op.alter_column('message_insights', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('message_insights', 'urgency',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('message_insights', 'objections',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('message_insights', 'products_mentioned',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'lifetime_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('customers', 'language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'uz'::character varying"))
    op.drop_column('customers', 'classification_corrected')
    op.drop_column('customers', 'classification_confidence')
    op.drop_column('customers', 'contact_type')
    op.create_index(op.f('ix_journey_events_workspace_customer'), 'customer_journey_events', ['workspace_id', 'customer_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_journey_events_conversation_id'), 'customer_journey_events', ['conversation_id'], unique=False)
    op.alter_column('customer_journey_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('customer_journey_events', 'event_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('conversations', 'needs_attention',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('conversations', 'pipeline_stage',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'new'::character varying"))
    op.create_index(op.f('ix_catalog_items_embedding'), 'catalog_items', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('catalog_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('catalog_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('catalog_items', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('catalog_items', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('catalog_items', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'UZS'::character varying"))
    op.alter_column('catalog_item_images', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_business_knowledge_workspace_active'), 'business_knowledge', ['workspace_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_business_knowledge_embedding'), 'business_knowledge', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('business_knowledge', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('business_knowledge', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('business_knowledge', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('business_knowledge', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('business_knowledge', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'faq'::character varying"))
    op.add_column('ai_training_data', sa.Column('action_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ai_training_data', sa.Column('context_snapshot_ref', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_ai_training_data_action_id_operator_actions'), 'ai_training_data', 'operator_actions', ['action_id'], ['id'])
    op.create_index(op.f('ix_ai_training_data_workspace_id'), 'ai_training_data', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_ai_training_data_action_id'), 'ai_training_data', ['action_id'], unique=False)
    op.alter_column('ai_training_data', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_training_data', 'signal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'1'::double precision"))
    op.create_index(op.f('ix_ai_replies_override_reason'), 'ai_replies', ['override_reason'], unique=False)
    op.alter_column('ai_replies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_replies', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.drop_column('ai_replies', 'split_messages')
    op.drop_column('ai_replies', 'chips')
    op.create_table('operator_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('channel', sa.VARCHAR(length=20), server_default=sa.text("'dm'::character varying"), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['operator_actions.id'], name=op.f('operator_events_action_id_fkey')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('operator_events_conversation_id_fkey')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('operator_events_customer_id_fkey')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('operator_events_workspace_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('operator_events_pkey')),
    sa.UniqueConstraint('event_id', name=op.f('uq_operator_events_event_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_operator_events_workspace_id'), 'operator_events', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_operator_events_occurred_at'), 'operator_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_operator_events_event_type'), 'operator_events', ['event_type'], unique=False)
    op.create_table('pipeline_stages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('color', sa.TEXT(), server_default=sa.text("'#6B7280'::text"), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_terminal', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('pipeline_stages_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pipeline_stages_pkey')),
    sa.UniqueConstraint('workspace_id', 'slug', name=op.f('uq_pipeline_stages_workspace_slug'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_pipeline_stages_workspace_id'), 'pipeline_stages', ['workspace_id'], unique=False)
    op.create_table('operator_actions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('channel', sa.VARCHAR(length=20), server_default=sa.text("'dm'::character varying"), autoincrement=False, nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('risk_tier', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('execution_mode', sa.VARCHAR(length=20), server_default=sa.text("'draft'::character varying"), autoincrement=False, nullable=False),
    sa.Column('reasoning_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('policy_checks', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('source_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'decided'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('executed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('operator_actions_conversation_id_fkey')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('operator_actions_customer_id_fkey')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('operator_actions_workspace_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('operator_actions_pkey'))
    )
    op.create_index(op.f('ix_operator_actions_workspace_id'), 'operator_actions', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_operator_actions_created_at'), 'operator_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_operator_actions_conversation_id'), 'operator_actions', ['conversation_id'], unique=False)
    op.create_table('metric_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('metric_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('metric_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('metric_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('metric_snapshots_workspace_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('metric_snapshots_pkey')),
    sa.UniqueConstraint('workspace_id', 'metric_name', 'metric_date', name=op.f('uq_metric_snapshots_workspace_metric_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_metric_snapshots_workspace_id'), 'metric_snapshots', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_metric_snapshots_metric_date'), 'metric_snapshots', ['metric_date'], unique=False)
    op.drop_table('draft_actions')
    op.drop_table('voice_profiles')
    op.drop_table('learning_signals')
    # ### end Alembic commands ###
