export const uz = {
  // Auth
  auth: {
    welcome: "Xush kelibsiz",
    signIn: "Kirish",
    signUp: "Ro'yxatdan o'tish",
    phone: "Telefon raqam",
    password: "Parol",
    phonePlaceholder: "+998 90 123 45 67",
    signingIn: "Kirilmoqda...",
    wrongCredentials: "Telefon raqam yoki parol noto'g'ri",
    networkError: "Tarmoq xatosi. Qayta urinib ko'ring.",
    noAccount: "Hisobingiz yo'qmi?",
    hasAccount: "Hisobingiz bormi?",
    createAccount: "Hisob yarating",
    brandHeadline: "AI sotuvchi yordamchingiz",
    brandSubtext: "Telegram mijozlaringizga tezkor va professional javob bering",
    fullName: "Ism",
    fullNamePlaceholder: "Alisher Karimov",
    creatingAccount: "Yaratilmoqda...",
    accountExists: "Bu raqam allaqachon ro'yxatdan o'tgan",
    startJourney: "OQIM bilan boshlang",
    existingAccount: "Hisobim bor",
    newAccount: "Yangi boshlayman",
    existingAccountDesc: "Telefon raqam va parol bilan kiring",
    newAccountDesc: "Telegramni ulab, AI ni sozlab chiqing",
    useTelegramPhone: "Telegram raqamidan foydalanish",
    useAnotherPhone: "Boshqa raqam ishlatish",
    loginPhoneHint: "Keyingi kirishlar uchun shu raqam ishlatiladi",
  },

  // Landing page
  landing: {
    heroTitle: "Telegramda sizning AI klonengiz",
    heroSubtitle:
      "Mijozlar yozadi — AI sizning ovozingizda javob beradi. Tasdiqlang, tahrirlang yoki avtomatik yuboring.",
    demoCustomerName: "Sardor",
    demoCustomerMsg: "Kechki ingliz tili guruhi bormi? Narxi qancha?",
    demoReplyLabel: "AI javob taklifi",
    demoReplyText:
      "Ha, kechki guruh bor. Darslar 19:00 da boshlanadi, oyiga 650 000 so'm. Joy band qilib qo'yaymi?",
    demoApprove: "Tasdiqlash",
    demoEdit: "Tahrirlash",
    metricSpeed: "~2 soniya",
    metricSpeedLabel: "javob vaqti",
    metricUptime: "24/7",
    metricUptimeLabel: "doimiy faol",
    metricSetup: "1 daqiqa",
    metricSetupLabel: "o'rnatish vaqti",
  },

  // Conversations
  conversations: {
    title: "Suhbatlar",
    search: "Suhbatlarni qidirish...",
    all: "Hammasi",
    unread: "O'qilmagan",
    needsFollowup: "Javob kerak",
    selectConversation: "Suhbatni tanlang",
    empty: "Suhbatlar yo'q",
    emptyDescription: "Mijozlar xabar yozganda bu yerda ko'rinadi",
    tabsLabel: "Suhbat ko'rinishi",
    tabs: {
      chats: "Chatlar",
      replies: "Javoblar",
      pipeline: "Savdo yo'li",
    },
    syncing: "Sinxronlash",
    syncingProgress: "ta chatdan",
    syncFailedChats: "{count} ta chat sinxronlanmadi — keyingi safar qayta uriniladi",
    replyIndicator: "AI javob tayyor",
    aiThinking: "AI javob tayyorlamoqda...",
    confidenceLabel: "AI ishonch darajasi",
    noMessages: "Xabar yo'q",
    composePlaceholder: "Xabar yozing...",
    selectChat: "Suhbatni tanlang",
    today: "Bugun",
    yesterday: "Kecha",
    voice: "Ovozli xabar",
    document: "Fayl",
    forwarded: "Yuborilgan:",
    edited: "tahrirlangan",
    customers: "Mijozlar",
    personal: "Shaxsiy",
    hasReply: "Javob taklifi bor",
    loadingMore: "Yana yuklanmoqda...",
    historyGap: "Bu yerda tarix oynasi uzilgan. Eski xabarlar faqat so'ralganda yuklanadi.",
    playVoice: "Ijro etish",
    pauseVoice: "To'xtatish",
    nowPlaying: "Hozir ijro etilyapti",
    previousTrack: "Oldingi media",
    nextTrack: "Keyingi media",
    playbackSpeed: "Ijro tezligi",
    mediaSeek: "Media ichida surish",
    typing: "yozmoqda",
    newMessages: "yangi xabar",
    scrollToBottom: "Pastga",
    videoMessage: "Video",
    videoNote: "Dumaloq video",
    mediaPreparing: "Media tayyorlanmoqda",
    mediaRetrying: "Media qayta yuklanadi",
    mediaUnavailable: "Media mavjud emas",
    stickerMessage: "Stiker",
    gifMessage: "GIF",
    contactMessage: "Kontakt",
    locationMessage: "Joylashuv",
    openInMaps: "Xaritada ochish",
    download: "Yuklab olish",
    audioMessage: "Audio",
    sending: "Yuborilmoqda...",
    failed: "Yuborilmadi",
    sent: "Telegramga yetdi",
    read: "O‘qildi",
    deliveryUncertain: "Telegram tasdig‘i kutilmoqda",
    allMessagesLoaded: "Barcha xabarlar yuklandi",
    loadError: "Xabarlarni yuklashda xatolik",
    retry: "Qayta urinish",
    messageNotFound: "Xabar topilmadi",
    replyTo: "Javob",
    you: "Siz",
    photo: "Rasm",
    photoOf: "Rasm",
    back: "Ortga",
    // Raw Telegram media class name mappings (from GramJS className)
    mediaLabels: {
      MessageMediaPhoto: "Rasm",
      MessageMediaDocument: "Fayl",
      MessageMediaGeo: "Joylashuv",
      MessageMediaGeoLive: "Joylashuv",
      MessageMediaContact: "Kontakt",
      MessageMediaWebPage: "Havola",
      MessageMediaPoll: "So'rovnoma",
      MessageMediaVenue: "Joylashuv",
      MessageMediaGame: "O'yin",
      MessageMediaInvoice: "Hisob",
      MessageMediaDice: "Emoji",
    } as Record<string, string>,
    mediaFallback: "Media",
    // Conversation header
    header: {
      lastSeen: "oxirgi faollik",
      online: "onlayn",
    },
  },

  // Customer panel
  customer: {
    phone: "Telefon",
    contactType: "Turi",
    stage: "Bosqich",
    notes: "Eslatmalar",
    notesPlaceholder: "Eslatma qo'shing...",
    firstSeen: "Birinchi murojaat",
    lastSeen: "Oxirgi murojaat",
    types: {
      customer: "Mijoz",
      supplier: "Ta'minotchi",
      personal: "Shaxsiy",
      work: "Ish",
      group: "Guruh",
    } as Record<string, string>,
    address: "Manzil",
    aiMuted: "AI yordamchisiz",
    aiMutedDescription: "Bu kontakt uchun AI javob yozmaydi",
    latestMessage: "Oxirgi xabar",
    nextBestAction: "Keyingi ish",
    aiReply: "AI javob taklifi",
    replyReady: "Tayyor",
  },

  // Customers page
  customers: {
    title: "Mijozlar",
    search: "Mijozlarni qidirish...",
    empty: "Mijozlar yo'q",
    emptyDescription: "Telegram orqali ingestiya qilingandan keyin mijozlar bu yerda ko'rinadi",
    export: "Eksport (CSV)",
    aiSummary: "AI profil yaratish",
    lifetimeValue: "Umumiy qiymat",
    conversationCount: "Suhbatlar",
    newThisWeek: "Bu hafta yangi",
    avgLtv: "O'rtacha LTV",
    total: "Jami",
    noBrief: "AI brifingi hali yo'q — suhbat tarixi yetarli emas.",
    needsAttention: "Diqqat talab qiladi",
    allStages: "Barchasi",
    stages: {
      new: "Yangi",
      qualified: "Malakali",
      negotiation: "Kelishuv",
      negotiating: "Kelishuv",
      proposal: "Taklif",
      payment: "To'lov",
      delivery: "Yetkazish",
      waiting: "Kutilmoqda",
      won: "Buyurtma",
      lost: "Sovuq",
      manual_review: "Tekshirish",
    },
    openChat: "Chatni ochish",
    noFilterMatch: "Tanlovga mos mijozlar topilmadi",
    messages: "xabar",
  },

  compose: {
    replyReady: "Javob tayyor",
    replyingTo: "Javob bermoqda",
    confidence: {
      green: "Ishonchli",
      yellow: "O'rtacha",
      red: "Tekshiring",
    },
    send: "Yuborish",
    edit: "Tahrirlash",
    dismiss: "Bekor qilish",
    regenerating: "Qayta yozilmoqda...",
    customInstruction: "Boshqa ko'rsatma...",
    messageCount: "ta xabar",
    saveSend: "Saqlash va yuborish",
    cancel: "Bekor qilish",
    emptyWarning: "Bo'sh javob yuborib bo'lmaydi",
    charWarning: "Telegram limiti: 4096 belgi",
    versionNew: "yangi",
    versionCount: "variant",
    // Dismiss reasons
    dismissReason: "Sabab (ixtiyoriy)",
    dismissReasons: {
      bad_tone: "Noto'g'ri ohang",
      incorrect_fact: "Noto'g'ri ma'lumot",
      other: "Kerak emas",
    } as Record<string, string>,
    dismissLearning: "AI bu tuzatishdan o'rganadi",
    // Delivery status
    sending: "Yuborilmoqda...",
    sent: "Telegramga yetdi",
    read: "O‘qildi",
    failed: "Yuborilmadi",
    deliveryUncertain: "Telegram tasdig‘i kutilmoqda",
    retry: "Qayta yuborish",
    retryExhausted: "Qayta urinish tugadi",
    // Stale reply
    staleWarning: "yangi xabar keldi. Qayta yozilsinmi?",
    staleRegenerate: "Yangilash",
    blockedReasons: {
      awaiting_media_hydration: "Media hali tayyor emas. Javob taklifi keyinroq yangilanadi.",
      existing_ai_reply: "Bu xabar uchun javob taklifi allaqachon mavjud.",
      seller_replied: "Suhbat davom etib ketgan. Yangi javob kerak emas.",
      superseded_by_newer_customer_message: "Mijoz yangi xabar yubordi. Eski javob taklifi yangilanmaydi.",
      trigger_deleted: "Asosiy xabar o'chirilgan. Javob taklifi yangilanmaydi.",
      trigger_missing: "Asosiy xabar topilmadi. Javob taklifi yangilanmaydi.",
    } as Record<string, string>,
  },

  sellerAgentReplies: {
    thinking: "AI javob yozmoqda...",
    thinkingFailed: "AI javob yoza olmadi",
    sent: "Yuborildi",
    deliveryFailed: "Xabar yuborilmadi, javob taklifi qaytarildi",
    deliveryUnknown: "Telegram javobni olgan bo'lishi mumkin. Echo tasdig'ini kutyapmiz.",
    autopilotEligible: "to'g'ri javob bermoqda",
    autopilotEnable: "Yoqish",
    autopilotNotNow: "Hali emas",
    autopilotQuestion: "Yashil javoblarni avtomatik yuborishni yoqaymi?",
    autopilotReviewed: "ta xabardan",
    autopilotApproved: "tasi o'zgartirishsiz yuborildi",
    revertSuggestion: "Oxirgi 3 ta AI javobini o'zgartirdingiz. Qo'lda tasdiqlash rejimiga qaytaymi?",
    revertYes: "Ha, qaytarish",
    revertNo: "Yo'q, davom etish",
    ghostSummary: "AI javob yubordi siz yo'q bo'lganingizda",
    ghostViewAll: "Hammasini ko'rish",
    staleChips: "Yangi xabarlar keldi",
    refresh: "Yangilash",
    reconnecting: "Qayta ulanmoqda...",
    reconnected: "Ulandi",
    aiLabel: "AI",
  },

  activity: {
    sessionRecoveryChecking: "Suhbatlar qayta tekshirilmoqda...",
    sessionRecoveryComplete: "Suhbatlar yangilandi",
  },

  workspaceUi: {
    search: "Chat, mijoz, katalog bo‘yicha qidirish",
    runtime: "Holat",
    connected: "Ulangan",
    ready: "Tayyor",
    learning: "O‘rganmoqda",
    modules: {
      conversations: {
        label: "Suhbatlar",
        description: "Pipeline, chat va javoblar",
        surfaces: ["Pipeline", "Suhbatlar", "Javoblar", "Mijoz paneli", "Media holati"],
      },
      replies: {
        label: "Javoblar",
        description: "Tasdiqlash, tahrir va o‘rganish",
        surfaces: ["Tasdiqlash navbati", "Tahrirlar", "Ovoz o‘rganish", "Avtopilot chegarasi"],
      },
      brain: {
        label: "Bilim",
        description: "Katalog, javoblar, qoidalar, uslub",
        surfaces: ["Katalog", "Bilim bazasi", "Qoidalar", "Yozish uslubi", "Suhbat namunalari", "Kompaniya profili"],
      },
      sources: {
        label: "Manbalar",
        description: "Fayl, sayt, Telegram va media o‘qilishi",
        surfaces: ["Jonli manbalar", "Qayta o‘qish", "Muammolar", "Arxiv", "Dalillar"],
      },
      intelligence: {
        label: "Aql",
        description: "Agentlar, ko‘nikmalar, qoidalar",
        surfaces: ["Agentlar", "Ko‘nikmalar", "Qoidalar", "Uslub", "Avtopilot chegarasi"],
      },
      actions: {
        label: "Amallar",
        description: "Agent takliflari, ruxsat va bajarish",
        surfaces: ["Tasdiq kerak", "Rejada", "Ishlayapti", "Tugadi", "Xato", "Audit"],
      },
      tasks: {
        label: "Vazifalar",
        description: "Egasi bajaradigan ishlar",
        surfaces: ["Bugungi vazifalar", "Taklif qilingan vazifalar", "Uchrashuvlar", "Yetkazish", "To‘lov tekshirish"],
      },
      integrations: {
        label: "Integratsiyalar",
        description: "Telegram va boshqa ulanishlar",
        surfaces: ["Telegram", "Instagram", "Bitrix", "amoCRM", "Calendar", "POS"],
      },
      settings: {
        label: "Sozlamalar",
        description: "Workspace, ruxsat va xarajat",
        surfaces: ["Ish joyi", "Ruxsat", "Model va prompt cache", "Limit va xarajat", "Audit"],
      },
      agents: {
        label: "Agentlar",
        description: "Sotuvchi, qayta jalb qilish, tahlil va avtopilot",
        surfaces: ["Sotuvchi agent", "Qayta jalb qilish", "Biznes tahlilchi", "Avtopilot", "AI sozlamalari"],
      },
      crm: {
        label: "CRM",
        description: "Mijozlar va voronkalar",
        surfaces: ["Voronkalar", "Bosqichlar"],
      },
    },
    rightRail: {
      title: "Faoliyat",
      tabs: {
        runs: "Jarayon",
        needsApproval: "Ruxsat kerak",
        proposed: "Taklif",
        done: "Bajarildi",
        summary: "Xulosa",
      },
      empty: {
        runs: "Agent ish boshlaganda nima qilayotgani shu yerda ko‘rinadi.",
        needsApproval: "Ruxsat kutayotgan ish yo‘q.",
        proposed: "Hali taklif yo‘q.",
        done: "Bugun bajarilgan ish yo‘q.",
        summary: "Workspace tinch.",
      },
      bi: {
        placeholder: "BI agentdan so‘rang: \"Bu hafta nima sotildi?\"",
        send: "Yuborish",
      },
    },
    brain: {
      title: "Bilim markazi",
      eyebrow: "Kompaniya xotirasi",
      description: "Mijozga javob berish uchun kerakli ma’lumot shu yerda: katalog, javoblar, qoidalar, yozish uslubi, suhbat namunalari va kompaniya profili. Mijoz holati alohida sahifada turadi.",
      search: "Bilim ichidan qidirish",
      statsKnowledge: "Bilim",
      statsRules: "Qoidalar",
      tabs: {
        catalog: "Katalog",
        knowledge: "Bilim bazasi",
        rules: "Qoidalar",
        voice: "Yozish uslubi",
        pairs: "Suhbat namunalari",
        company: "Kompaniya profili",
      },
      descriptions: {
        catalog: "Mahsulot, variant, narx, media va mavjudlik dalillari.",
        knowledge: "Biznes faktlari, FAQ, kafolat, yetkazish va servis javoblari.",
        rules: "Egasining ko‘rsatmalari: yetkazish, uchrashuv, qaytarish, handoff.",
        voice: "Sotuvchi qanday yozadi, sotadi, aniqlashtiradi va savdoni yakunlaydi.",
        pairs: "Sotuvchi tahrirlari va oldingi yaxshi javob namunalari.",
        company: "Ish vaqti, filiallar, yetkazish hududi, to‘lov va integratsiyalar.",
      },
      sources: {
        groundingTitle: "Agentlar nimaga tayanadi",
        groundingDesc: "Javoblar faqat tasdiqlangan yoki ko‘rib chiqilayotgan dalilga suyanadi.",
        capabilityTitle: "OQIM nimalarni o‘qiy oladi",
        capabilityDesc: "Savdo ham, support ham, kurs yoki dastur hujjati ham bitta tartibda o‘rganiladi.",
        noCatalogConfusion: "Katalogga majburlamaydi",
        listTitle: "Manbalar holati",
        listDesc: "Har bir manba bo‘laklarga ajratiladi. Muammo bo‘lsa, qaysi manba to‘xtaganini ko‘rasiz.",
        addTitle: "Manba qo‘shish",
        addDesc: "Sayt, kanal, PDF, jadval, matn yoki ovoz qo‘shing. OQIM undan katalog, FAQ, qoida, uslub yoki suhbat namunasi chiqaradi.",
        newBadge: "Yangi",
        add: "Manba qo‘shish",
        adding: "O‘rganilmoqda...",
        chooseFile: "Fayl tanlash",
        fileHint: "PDF, CSV, XLSX, TXT yoki audio",
        startRecording: "Mikrofondan yozish",
        stopRecording: "To‘xtatish",
        audioReady: "Ovoz tayyor",
        recordingUnavailable: "Brauzer mikrofon yozishni qo‘llamayapti.",
        recordingFailed: "Mikrofondan yozib bo‘lmadi. Ruxsatni tekshiring yoki audio fayl yuklang.",
        progressTitle: "O‘rganish jarayoni",
        progressLabel: "Tayyorlanish",
        progressDesc: (learned: number, review: number, retrying: number) =>
          `${learned} ta manba tayyor. ${review} tasi tekshirishda. ${retrying} tasi qayta urinadi.`,
        kinds: {
          website: "Sayt",
          telegram: "Telegram",
          file: "PDF / fayl",
          voice: "Ovoz / qoida",
          history: "Suhbat tarixi",
        },
        modes: {
          website: "Sayt",
          telegram: "Telegram",
          file: "Fayl",
          text: "Matn",
          voice: "Ovoz",
        },
        placeholders: {
          website: "https://kompaniya.uz yoki support sahifasi",
          telegram: "@kanal yoki kanal havolasi",
          text: "FAQ, qoidalar, servis javoblari, mahsulot yoki kompaniya uslubini kiriting.",
          voice: "Ovozdagi qoida, uslub yoki support javobini yozib qo‘shish mumkin.",
        },
        capabilities: {
          sales: {
            title: "Savdo",
            description: "Mahsulot, narx, zaxira, rasm va takliflar.",
          },
          support: {
            title: "Support",
            description: "FAQ, qaytarish, yetkazish, SLA va eskalatsiya.",
          },
          programs: {
            title: "Kurs / dastur",
            description: "PDF, muddat, grant, sertifikat va qabul shartlari.",
          },
          company: {
            title: "Kompaniya",
            description: "Ish vaqti, kontakt, filial, to‘lov va xizmatlar.",
          },
          voice: {
            title: "Uslub",
            description: "Ovoz, eski suhbatlar va sotuvchi tuzatishlari.",
          },
        },
        statuses: {
          learning: "O‘rganilyapti",
          indexed: "O‘qildi",
          learned: "O‘rganildi",
          needs_review: "Tekshirish",
          retrying: "Qayta urinadi",
          failed: "Muammo",
          missing: "Yetishmaydi",
          conflict: "Konflikt",
          empty: "Bo‘sh",
        },
      },
      review: {
        title: "Tekshiruv navbati",
        description: "Agent ishlatishidan oldin noaniq javob, qoida va uslubni tekshiring.",
        empty: "Hozir tekshiradigan yangi fakt yo‘q.",
        fact: "Fakt",
        needsText: "Nima tasdiqlanishi ko‘rinmayapti. Avval tahrirlang.",
        edit: "Tahrirlash",
        correctText: "To‘g‘ri matn",
        saveEdit: "Tuzatib tasdiqlash",
        saveActive: "Saqlash",
        mergeLabel: "Dublikat bilan birlashtirish",
        mergePlaceholder: "Asosiy faktni tanlang",
        merge: "Birlashtirish",
        approve: "Tasdiqlash",
        reject: "Rad etish",
        approved: "Tasdiqlandi",
        rejected: "Rad etildi",
        edited: "Tuzatildi",
        updated: "Saqlangan fakt agentlar uchun yangilandi.",
        failed: "Amal bajarilmadi. Qayta urinib ko‘ring.",
        more: (count: number) => `Yana ${count} ta fakt bor`,
        statuses: {
          active: "Ishlatiladi",
          confirmed: "Tasdiqlangan",
          proposed: "Tekshirish",
          degraded: "Yordam kerak",
          conflict: "Konflikt",
          rejected: "Rad etilgan",
          superseded: "Almashtirilgan",
        },
        labels: {
          sources: "Manba",
          catalog: "Katalog",
          knowledge: "Javob",
          rules: "Qoida",
          voice: "Uslub",
          pairs: "Juftlik",
          company: "Kompaniya",
        },
      },
    },
    intelligence: {
      title: "Mijozlar holati",
      eyebrow: "Mijozlar va savdo",
      description: "Mijoz kim, qaysi bosqichda, nima sotib olmoqchi, nima va’da qilingan va qachon qayta yozish kerakligini bir joyda ko‘rsatadi.",
      investigate: "Tekshirish",
      planCampaign: "Kampaniya rejalash",
      actionInbox: "Ruxsat navbati",
      stateMap: "Mijoz holati xaritasi",
      boundary: "Avtopilot qachon so‘raydi",
      insights: "Savdo xulosalari",
      productDemand: "Mahsulot talabi",
      channelHealth: "Kanal holati",
      emptyInsights: "Hali savdo xulosalari yo‘q.",
      metrics: {
        customers: "Mijozlar",
        opportunities: "Imkoniyatlar",
        replyNeeded: "Javob kerak",
        orders: "Buyurtmalar",
        stalled: "To‘xtaganlar",
      },
      planes: {
        customer: "Mijoz holati",
        opportunity: "Imkoniyat holati",
        order: "Buyurtma va to‘lov",
        delivery: "Yetkazish",
        task: "Biznes vazifa",
        followup: "Qayta yozish",
      },
    },
    agents: {
      title: "Agentlar",
      eyebrow: "OQIM jamoasi",
      description: "Sotuvchi agent javob yozadi, qayta jalb qilish sovigan mijozlarni topadi, biznes tahlilchi savdo savollariga javob beradi, avtopilot esa ruxsat chegarasini ushlaydi.",
      loop: "Agent qanday ishlaydi",
      autopilot: "Avtopilot qoidasi",
      openReplies: "Javoblar",
      openCrm: "Mijoz holati",
      openActions: "Takliflar",
      openSettings: "Sozlamalar",
    },
    conversations: {
      title: "Suhbatlar",
      eyebrow: "Sotuvchi workspace",
      pipeline: "Pipeline",
      conversations: "Suhbatlar",
      replies: "Javoblar",
      pipelineDescription: "Bosqichlar suhbatlardan avtomatik yangilanadi va mijozlar qayerda turganini ko‘rsatadi.",
      conversationsDescription: "Mijoz yozishmalari, oxirgi xabarlar va javob holati shu yerda boshqariladi.",
      replyDescription: "Javob taklifi chat loop ichida: tasdiqlash, tahrirlash, o‘rganish va suhbatga qaytish.",
      activeConversation: "Tanlangan suhbat",
      loadedCount: (count: number) => `${count} suhbat yuklandi`,
      updating: "Yangilanmoqda",
      sellerAgent: "Sotuvchi agent",
      decisionPanelTitle: "Qaror, dalil, amal",
      sellerAgentEmpty: "Sotuvchi agent mijoz holati, dalil va javob qarorini shu yerda yig‘adi.",
      actionProposals: "Keyingi amallar",
      conversationEvidence: "Suhbat dalili",
      sourceEvidence: "Manba dalili",
      mediaEvidence: "Media dalil",
      systemEvidence: "Tizim dalili",
    },
  },

  // Telegram connect (onboarding route)
  connect: {
    phoneTitle: "Telegram raqamingizni kiriting",
    phoneSubtitle: "Kod Telegram ilovasiga yuboriladi. SMS yo'liga o'tmaymiz.",
    sendCode: "Ilovaga kod yuborish",
    useQr: "QR orqali kirish",
    usePhone: "Telefon orqali davom etish",
    codeTitle: "Kod yuborildi",
    codeHintGeneric: "Telegram kod yuborishga harakat qildi. Holatni shu oynada ko'ramiz.",
    codeHintApp: "Telegram kod ochiq turgan akkaunt sessiyalariga yuborilganini bildirdi.",
    codeHintAppDegraded: "Telegram ilovaga kod yuborishini kutgandik, lekin Telegram boshqa tasdiqlash yo'lini qaytardi. Agar kod kelmasa, QR orqali kiring yoki keyingi yo'lni qo'lda sinang.",
    codeHintSms: "Telegram SMS orqali kod yuborilganini bildirdi.",
    codeHintCall: "Telegram kod telefon qo'ng'irog'i orqali yuborilishini bildirdi.",
    codeHintFlashCall: "Telegram kod flash call orqali yuborilishini bildirdi.",
    codeHintMissedCall: "Telegram kod missed call orqali yuborilishini bildirdi.",
    codeTimeoutPrefix: "Kod kelmasa, OQIM taxminan",
    codeTimeoutSuffix: "soniyadan keyin keyingi yo'l ochiladi",
    codeNextRetryHint: "Keyingi yo'lni faqat siz bosganingizda sinaymiz.",
    codeRecoveryWaiting: "Kod kelmasa, keyingi tasdiqlash yo'lini qo'lda sinashingiz mumkin.",
    codeRecoverySwitching: "OQIM keyingi tasdiqlash yo'lini sinayapti...",
    codeRecoveryReady: "Keyingi tasdiqlash yo'lini sinash",
    codeAppNoFallbackTitle: "Kod ko'rinmayaptimi?",
    codeAppNoFallback1: "Telegramdagi rasmiy “Telegram” chatini, arxivni va boshqa ochiq qurilmalarni tekshiring.",
    codeAppNoFallback2: "Agar eski telefon yoki desktopda sessiya ochiq bo'lsa, kod ko'pincha o'sha yerga boradi.",
    codeAppNoFallback3: "Ochiq sessiyani o'chirmang. Avval QR orqali ulang yoki Telegram Web/Desktopda shu akkaunt ochiq turganini tekshiring.",
    openTelegramWeb: "Telegram Webni ochish",
    tryAlternateCodeRoute: "Boshqa yo'l bilan kod so'rash",
    tryAlternateCodeRouteHint: "OQIM kodni boshqa Telegram ulanishi orqali qayta so'raydi. Bu ba'zan kod ilovada ko'rinishiga yordam beradi.",
    codePlaceholder: "12345",
    verify: "Tasdiqlash",
    twoFaTitle: "Ikki bosqichli parol",
    twoFaSubtitle: "Telegram sozlamalarida o'rnatilgan parolingizni kiriting",
    twoFaPrompt: "Ikki bosqichli parolingizni kiriting",
    codeExpired: "Kod eskirdi. Qayta yuborilsinmi?",
    resend: "Keyingi yo'lni sinash",
    resendAfter: "Keyingi yo'l",
    invalidCode: "Kod noto'g'ri",
    wrongPassword: "Parol noto'g'ri",
    phoneInvalid: "Bu Telegram raqami noto'g'ri ko'rinyapti. Raqamni tekshirib qayta urinib ko'ring.",
    phoneBanned: "Telegram bu raqam orqali kirishga ruxsat bermadi. Boshqa raqam yoki QR orqali urinib ko'ring.",
    phoneCodeSendFailed: "Telegram telefon orqali kodni yetkazmadi. OQIM boshqa kirish yo'lini ko'rsatadi.",
    deviceCodeUnavailable: "Telegram bu raqam uchun ilova kodini bermadi. Raqam Telegramda ochiq turganini tekshiring yoki QR orqali kiring.",
    rateLimited: "Telegram urinishlarni vaqtincha chekladi. OQIM holatni saqlab qo'ydi va keyingi xavfsiz urinishni ko'rsatadi.",
    twoFaChecking: "Telegram parolni tekshirmoqda...",
    twoFaTimeout: "2FA kutish vaqti tugadi. Qayta urinib ko'ring.",
    serviceDown: "Xizmat vaqtincha ishlamayapti. Keyinroq urinib ko'ring.",
    connectLater: "Keyinroq sozlamalardan ulang",
    qrSubtitle: "SMS kutmaymiz. Telegram ilovasidan shu QR kodni tasdiqlang.",
    qrTitle: "QR kod orqali kirish",
    qrStep1: "Telefondan",
    qrStep1Bold: "Telegram",
    qrStep1End: "ni oching",
    qrStep2: "Sozlamalar → Qurilmalar → QR kodni skanerlash",
    qrStep3: "Telefoningizni bu ekranga yo'naltiring",
    qrLoading: "QR kod tayyorlanmoqda...",
    openTelegram: "Telegram ilovasini ochish",
    qrFailed: "QR orqali kirish muvaffaqiyatsiz bo'ldi. Qayta urinib ko'ring.",
    qrExpired: "QR kod eskirdi. Yangi kod tayyorlanmoqda...",
  },

  // Onboarding
  onboarding: {
    setup: "Sozlash",
    preparing: "OQIM tayyorlanmoqda",
    step: "qadam",
    voiceTitle: "Yozish uslubingiz o‘rganilmoqda",
    voiceExplain: "Xabarlaringizni o'qib, qanday yozishingizni tushunmoqda. Siz hech narsa qilmaysiz.",
    voiceAnalyzing: "ta xabar tahlil qilinmoqda",
    contactsTitle: "Mijozlaringiz aniqlandi",
    contactsExplain: "Kontaktlaringizdan mijoz va yetkazuvchilarni ajratdik. Faqat mijozlarga javob beramiz.",
    customers: "mijoz",
    totalContacts: "jami kontakt",
    noCustomers: "Mijozlar keyinroq avtomatik aniqlanadi",
    channelsTitle: "Mahsulotlaringiz qayerda?",
    channelsExplain: "Narx, mahsulot va xizmatlar bo‘yicha javob berish uchun kanalingizni tanlang. Keyinroq ham qo‘shishingiz mumkin.",
    scanAction: "Skanerlash",
    skip: "O'tkazish",
    loginHint: "Telegram hisobingiz bilan kiring",
    connecting: "Telegram bilan ulanmoqda...",
    success: "Muvaffaqiyatli!",
    qrTitle: "QR kod orqali kirish",
    qrStep1: "Telefondan",
    qrStep1Bold: "Telegram",
    qrStep1End: "ni oching",
    qrStep2: "Sozlamalar \u2192 Qurilmalar \u2192 QR kodni skanerlash",
    qrStep3: "Telefoningizni bu ekranga yo\u2018naltiring",
    twoFaError: "2FA hozircha qo\u2018llab-quvvatlanmaydi. Iltimos, vaqtincha o\u2018chiring.",
    twoFaPrompt: "Ikki bosqichli parolingizni kiriting",
    twoFaPlaceholder: "Parol",
    twoFaSubmit: "Kirish",
    wrongPassword: "Parol noto\u2018g\u2018ri. Qayta urinib ko\u2018ring.",
    connectionLost: "Aloqa uzildi. Qayta urinib ko\u2018ring.",
    telegramLoading: "Telegram yuklanmoqda...",
    subtitle: "Telegram mijozlaringiz bilan bitta joyda ishlang",
    authFailed: "Kirish muvaffaqiyatsiz — qayta urinib ko'ring",
    allReady: "Hammasi tayyor!",
    aiStarted: "OQIM ishga tushdi. Suhbatlarga o‘ting.",
    goToConversations: "Suhbatlarga o'tish",
    syncing: "Tayyorlanmoqda...",
    telegramConnected: "Telegram ulandi",
    serviceDown: "Xizmat vaqtincha ishlamayapti. Keyinroq urinib ko'ring.",
    existingAccountFound: "Bu Telegram oldingi OQIM hisobiga tegishli. O'sha hisobga kirdik.",
    existingAccountReconnected: "Telegram qayta ulandi. OQIM hisobingiz va suhbatlaringiz joyida.",
    reconnectTitle: "Telegramni qayta ulang",
    reconnectDesc: "OQIM hisobingiz saqlangan. Telegram ulanishini yangilasangiz, shu workspace davom etadi.",
    reconnectRevokedDesc: "Telegram sessiyasi bekor qilingan bo'lishi mumkin. Qayta ulasangiz, shu workspace davom etadi.",
    reconnectIdentityMismatchDesc: "Bu workspace boshqa Telegram hisobiga ulangan. To'g'ri Telegram hisobingiz bilan qayta ulang.",
    reconnectAlreadyConnectedTitle: "Telegram ulangan",
    reconnectAlreadyConnectedDesc: "Bu workspace to'g'ri Telegram hisobiga ulangan. Qayta kirish shart emas.",
    continueSetup: "Davom etish",
    finishError: "Sozlashni yakunlab bo'lmadi. Qayta urinib ko'ring.",
    launch: {
      crumb: "Onboarding · yakuniy qadam",
      title: "OQIM ishga tushishga tayyor",
      subtitle: "Quyidagilarni o‘rgandi va shu asosda ishlay oladi.",
      // Block 1 — learned counts
      learnedTitle: "OQIM nimani o‘rgandi",
      learnedBusiness: "Biznes bo‘limlari",
      learnedAgent: "Agent bo‘limlari",
      learnedSkill: "Ko‘nikma namunalari",
      learnedReady: (ready: number, total: number) => `${ready}/${total} tayyor`,
      learnedCount: (n: number) => `${n} ta`,
      // Block 2 — agents + permission
      agentsTitle: "Agentlar",
      agentsSubtitle: "Quyidagi 5 agent shu workspace uchun tayyorlandi.",
      agentSeller: "Sotuvchi",
      agentSupport: "Qo‘llab-quvvatlash",
      agentCatalogUpdate: "Katalog yangilash",
      agentFollowUp: "Kuzatuv",
      agentBi: "Tahlil (BI)",
      agentBadgeReady: "Tayyor",
      permissionLabel: "Ruxsat",
      permissionAskAlways: "Tasdiqlash bilan",
      permissionAutoApprove: "Avtomatik tasdiq",
      permissionFullAccess: "To‘liq ruxsat",
      // Block 3 — first work
      firstWorkTitle: "Birinchi ishlar",
      firstWorkOne: "Yangi xabarlarni kuzatadi.",
      firstWorkTwo: "Javoblarni tayyorlaydi va tasdiqqa qo‘yadi.",
      firstWorkThree: "Muhim narsalarni eslatadi.",
      // Actions
      start: "Boshlash",
      later: "Keyin ko‘rib chiqaman",
      error: "Ishga tushirib bo‘lmadi. Qayta urinib ko‘ring.",
    },
    documents: {
      crumb: "Onboarding · 2-qadam",
      section: "Hujjatlar",
      tabBusiness: "Biznes",
      tabAgent: "Agent",
      tabSkill: "Ko‘nikma",
      tabCount: (current: number, total: number) => `${current}/${total}`,
      continue: "Davom etish",
      generateAll: "Hujjatlarni yaratish",
      generateStarted: "Hujjatlar yaratilmoqda",
      generateFailed: "Hujjatlarni yaratib bo‘lmadi. Qayta urinib ko‘ring.",
      statusApproved: "tasdiqlandi",
      statusProposed: "taklif",
      statusGenerating: "yozilmoqda",
      statusPending: "Navbatda",
      statusSkipped: "O‘tkazib yuborildi",
      accept: "Qabul",
      reject: "Rad et",
      edit: "Tahrir",
      degradedBody: "Ma’lumot yetishmadi. Manba qo‘shsangiz, OQIM bu bo‘limni to‘ldiradi.",
      // Right rail
      railReading: "Manbalardan o‘qilmoqda",
      railReadingEmpty: "Hali manba o‘qilmayapti.",
      railEvidence: "Dalillar",
      railEvidenceHint: "Tanlangan bo‘lim uchun manbalar shu yerda ko‘rinadi.",
      railEvidenceEmpty: "Bu bo‘limga hali dalil biriktirilmagan.",
      railEvidenceCount: (n: number) => `${n} ta dalil`,
      railConflicts: "Hal qilinishi kerak",
      railConflictsEmpty: "Hozircha hal qilinadigan ziddiyat yo‘q.",
      mobileSourcesTrigger: "Manbalar",
      mobileSourcesTitle: "Manbalar va dalillar",
      // Skill (Ko'nikma) tab
      skillDegradedTitle: "OQIM hali suhbatlaringizdan o‘rganmoqda",
      skillDegradedBody: "Ko‘nikma hujjati uchun kamida 5 ta yozishma kerak.",
      skillPendingTitle: "Ko‘nikma hali boshlanmadi",
      skillPendingBody: "Suhbatlar o‘qilgach, OQIM takrorlanuvchi savdo namunalarini ajratadi.",
      skillLearningTitle: "Ko‘nikma o‘rganilmoqda",
      skillLearningBody: "Suhbatlardan takrorlanuvchi namunalar ajratilyapti.",
      skillProposedTitle: "Ko‘nikma namunalari tayyor",
      skillProposedSubtitle: "Tasdiqlangan namunalar agent uslubiga qo‘shiladi.",
      skillCandidates: (n: number) => `${n} ta namuna topildi`,
      skillReviewedTitle: "Hammasi ko‘rib chiqildi",
      skillReviewedBody: "Barcha namunalar ko‘rib chiqildi. Yangi suhbatlardan yana o‘rganiladi.",
      // Skill candidate card (labeled fields + actions)
      skillWhenLabel: "Qachon",
      skillDoesLabel: "Nima qiladi",
      skillExampleLabel: "Namuna",
      skillEvidence: (n: number) => `${n} ta suhbatdan o‘rganildi`,
      skillApproved: "Ko‘nikma qo‘shildi",
      skillRejected: "Namuna olib tashlandi",
      skillActionError: "Amalni bajarib bo‘lmadi. Qayta urinib ko‘ring.",
      // Inline error banner
      streamError: "Holat olinmadi — qayta urinilmoqda",
      // AGENT.md path selector (Defaults / Speak / Upload)
      agentPaths: {
        title: "Agent uslubini belgilang",
        subtitle: "OQIM AGENT.md ni tayyorlaydi. Quyidagi yo‘llardan birini tanlang.",
        titleReady: "AGENT.md tayyor",
        subtitleReady: "Uslubni o‘zgartirib qayta yaratishingiz mumkin.",
        tabDefaults: "Tayyor",
        tabSpeak: "Ovozdan",
        tabUpload: "Yuklash",
        generate: "Yaratish",
        regenerate: "Qayta yaratish",
        generating: "Yaratilmoqda...",
        generateSuccess: "Agent qayta yozilmoqda",
        generateError: "Agentni yaratib bo‘lmadi. Qayta urinib ko‘ring.",
        defaultsBody:
          "Andoza va biznes ma’lumotidan foydalanib, sotuvchi agentni tayyorlaymiz.",
        speakBody: "Tugmani bosib, agent qanday gapirishini ayting.",
        speakStart: "Ovoz yozish",
        speakStop: "To‘xtatish",
        speakRecording: "Yozilyapti...",
        speakTranscribing: "Matnga aylantirilmoqda...",
        speakUnavailable:
          "Brauzer mikrofonni qo‘llamayapti. Quyiga yozib qo‘ying.",
        speakDegraded:
          "Audio tushunarli matn bermadi. Quyiga qo‘lda yozishingiz mumkin.",
        ownerInputLabel: "Sizning ko‘rsatmangiz",
        ownerInputPlaceholder:
          "Masalan: doim hurmat bilan, narxni so‘ralganda aniq ayt, qaytarib so‘ra.",
        uploadBody: "AGENT.md yoki SOP matnini joylang yoki .md/.txt fayl yuklang.",
        uploadFile: "Fayl yuklash (.md, .txt)",
        uploadPdfNote: "PDF hozircha qo‘llanmaydi.",
        uploadReadError: "Faylni o‘qib bo‘lmadi. .md yoki .txt yuklang.",
        emptyTitle: "Avval hujjatlar yaratilsin",
        emptyBody: "Agent tayyor bo‘lgach, uni shu yerda shakllantirasiz.",
      },
    },
    catalog: {
      title: "Mahsulotlar va bilim bazasi",
      subtitle: "Mijozlarga aniq javob berish uchun ma’lumot qo‘shing. Keyinroq ham qo‘shishingiz mumkin.",
      productsTab: "Mahsulotlar",
      knowledgeTab: "Bilim bazasi",
      uploadHint: "Faylni yuklang",
      extracting: "OQIM tahlil qilmoqda...",
      confirm: "Tasdiqlash",
      finish: "Yakunlash",
      savedCount: (n: number) => `${n} ta mahsulot saqlandi`,
      knowledgePlaceholder: "Biznes qoidalari, FAQ yoki hujjat matnini joylashtiring...",
      extract: "OQIM bilan ajratish",
      orUploadFile: "yoki fayl yuklang",
      knowledgeSavedCount: (n: number) => `${n} ta bilim saqlandi`,
    },
    scanning: "Skanerlanmoqda...",
    productsFound: "ta mahsulot topildi",
    knowledgeFound: "ta savol-javob topildi",
    noChannels: "Kanal topilmadi",
    noChannelsExplain: "Siz keyinroq katalogga mahsulotlarni qo'lda qo'shishingiz mumkin.",
    subscribers: "obunachi",
    members: "a'zo",
    lastPost: "Oxirgi post",
    readyTitle: "OQIM tayyor!",
    readyExplain: "Hammasi tayyor. OQIM endi mijozlarga javob taklif qila oladi.",
    start: "Boshlash",
    products: "mahsulot",
    knowledge: "bilim",
    voiceProfile: "ovoz profili",
    continue: "Davom etish",
    retry: "Qayta urinish",
    error: "Xatolik yuz berdi",
    timeRemaining: "Taxminan",
    minutesLeft: "daqiqa qoldi",
    preparing2: "Tayyorlanmoqda...",
    connectionCheck: "Ulanish tekshirilmoqda...",
    completed: "Yakunlandi",
    detecting: "Aniqlanmoqda",
    back: "Ortga",
    showAll: "Barchasini ko'rsatish",
    adminOnly: "Faqat siz boshqaradigan kanallar",

    // Step titles (6-step redesign)
    learningTitle: "Yozish uslubingiz o‘rganilmoqda",
    learningExplain: "Xabarlaringizni o'qib, qanday yozishingizni tushunmoqda. Siz hech narsa qilmaysiz.",
    catalogTitle: "Mahsulotlaringiz qayerda?",
    catalogExplain: "OQIM javob berishi uchun Telegram, sayt yoki fayldan birinchi manbani qo‘shing.",
    knowledgeTitle: "Bilim bazasi",
    knowledgeExplain: "Chatlardan topilgan ma’lumotlarni tekshiring. Qo‘shimcha qo‘shishingiz ham mumkin.",
    reviewTitle: "Tekshirish va tasdiqlash",
    reviewShort: "Tekshirish",
    reviewExplain: "Topilgan ma’lumotlarni tekshiring. Noto‘g‘ri bo‘lsa tahrirlang yoki o‘chiring.",

    // Section headers
    sectionContacts: "Kontaktlar",
    sectionVoice: "Ovoz profili",
    sectionKnowledge: "Bilim bazasi",
    sectionChatExtracted: "Chatlardan topildi",
    sectionAddMore: "Qo'shimcha qo'shish",

    // Source picker (catalog step)
    fromChannel: "Telegram kanaldan",
    fromChannelDesc: "Kanal postlaridagi mahsulotlarni avtomatik topadi",
    fromFile: "Fayldan yuklash",
    fromFileDesc: "Excel, PDF, rasm — narxlar ro'yxati",
    fromManual: "Qo'lda kiritish",
    fromManualDesc: "Mahsulotlarni bitta-bitta qo'shish",
    skipForNow: "Keyinroq qo'shaman",

    // File upload
    dropOrSelect: "Faylni tashlang yoki tanlang",
    acceptedFormats: "Excel (.xlsx), PDF, rasm (.jpg, .png)",
    maxSize: "Maksimum 10 MB",
    aiReadingFile: "OQIM faylni o‘qimoqda...",
    rowsFound: "ta qator topildi",

    // Review
    confirm: "Tasdiqlash",
    edit: "Tahrirlash",
    remove: "O'chirish",
    confirmAll: "Hammasini tasdiqlash",
    aiExtracted: "Topilgan",
    fromChat: "chatlardan",
    fromChannelLabel: "kanaldan",
    fromFileLabel: "fayldan",
    mentionedTimes: "marta aytilgan",
    lastMentioned: "oxirgi",

    // Voice profile
    aiUnderstood: "OQIM nimani tushundi",

    // Classify step (embedding-based grouped list)
    classify: {
      title: "Kontaktlarni tasniflash",
      subtitle: "Kontaktlar guruhlandi. Noto‘g‘ri bo‘lsa o‘zgartiring.",
      groups: {
        customer: "Mijozlar",
        personal: "Shaxsiy",
        supplier: "Ta'minotchilar",
        work: "Ish",
        family: "Oila",
      } as Record<string, string>,
      confirm: "Tasdiqlash",
      contactCount: (n: number) => `${n} ta kontakt`,
    },

    // Contact classification correction
    correctionHelps: "Tuzatishingiz keyingi javoblarni yaxshilaydi",
    searchContacts: "Qidirish...",
    allContacts: "Barchasi",
    showMore: "yana",
    showMoreSuffix: "ta",

    // Misc
    noDataFound: "Chatlardan ma'lumot topilmadi. Keyingi qadamda qo'lda qo'shishingiz mumkin.",
    processing: "Tayyorlanmoqda...",

    // Channel picker tabs
    tabs: {
      own: "Sizniki",
      all: "Barchasi",
      channels: "Kanallar",
      groups: "Guruhlar",
    },

    // Channel type / role badges
    admin: "boshqaruvchi",
    channelType: "kanal",
    groupType: "guruh",

    // Currency
    currency: "so'm",

    // Time range
    last3months: "oxirgi 3 oy",

    // Summary stats labels
    customerLabel: "mijoz",
    productLabel: "mahsulot",
    knowledgeBaseLabel: "bilim bazasi",

    // Buttons reused across views
    ready: "Tayyor",
    readyWithCount: (n: number, unit: string) => `Tayyor (${n} ${unit})`,
    add: "Qo'shish",
    searchPlaceholder: "Qidirish...",

    // Section labels (uppercase, in streaming feed)
    sections: {
      contacts: "KONTAKTLAR",
      voice: "OVOZ PROFILI",
      knowledge: "BILIM BAZASI",
    },

    // Contact type labels (used in streaming feed)
    contactTypes: {
      customer: "mijoz",
      personal: "shaxsiy",
      supplier: "yetkazuvchi",
      group: "guruh",
      work: "ish",
    },

    // Stats bar labels
    customerStat: "mijoz",
    supplierStat: "yetkazuvchi",
    personalStat: "shaxsiy",

    // Streaming feed event messages
    contactsFound: (contacts: number, channels: number) => `${contacts} suhbat ko‘rindi, ${channels} kanal topildi`,
    contactsDegraded: "Kontaktlarni ajratish vaqtincha to'liq yakunlanmadi. Qayta urinib ko'rish mumkin.",
    voiceCreating: (customers: number) => `Ovoz profili yaratilmoqda... (${customers} mijoz chatidan)`,
    voiceReady: (messages: number) => `Ovoz profili tayyor — ${messages} xabar`,
    voiceDegraded: (messages: number) => (
      messages > 0
        ? `Ovoz profili hali kuchsiz — ${messages} xabar`
        : "Ovoz profilini hozircha yaratib bo'lmadi"
    ),
    scanReadingPosts: "Kanal postlarini o'qimoqda...",
    scanExtractingProducts: "Mahsulotlar ajratilmoqda...",
    scanGroupingVariants: "Variantlarni guruhlash...",
    scanSaving: "Katalogga saqlanmoqda...",
    scanReadingComments: (count: number) => `${count} ta postdan savol-javob o'qimoqda...`,
    fileParsed: "Fayl o'qildi",

    // Voice profile one-liner
    voiceProfileReady: "Ovoz profili tayyor",
    exampleLabel: "namuna",

    // Intelligence moment (quick scan results)
    scan: {
      scanning: "Telegramni skanerlamoqda...",
      scanSubtitle: "Chatlaringizni o'qib, biznesingizni tushunmoqda",
      readingChats: "Chatlar o'qilmoqda...",
      analyzingVoice: "Yozish uslubingiz tahlil qilinmoqda...",
      customerCount: (n: number) => `${n} ta mijoz`,
      activeRecently: (n: number) => `${n} ta aktiv (7 kun)`,
      noColdLeads: "Barcha chatlar aktiv",
      daysAgo: (n: number) => `${n} kun oldin`,
      unanswered: "Javobsiz qolgan",
      customerSilent: "Mijoz kutmoqda",
      yourStyle: "Sizning uslubingiz",
      informal: "Norasmiy",
      formal: "Rasmiy",
      moderate: "O'rtacha",
      warm: "Iliq",
      cool: "Sovuq",
      short: "Qisqa xabarlar",
      medium: "O'rtacha xabarlar",
      long: "Uzun xabarlar",
      splitter: "Bir necha xabarda yozadi",
      oneShotStyle: "Bitta xabarda yozadi",
      ready: "OQIM tayyor",
      readySubtitle: "Orqa fonda to'liq o'rganish davom etmoqda",
      startUsing: "Boshlash",
      backgroundLearning: "Orqa fonda o'rganmoqda...",
      activeLabel: "aktiv (7 kun)",
      langUz: "O'zbek",
      langUzCyr: "Кириллча",
      langRu: "Ruscha",
      langEn: "Inglizcha",
      langMixed: "Aralash",
    },
    chooseTitle: "Qanday boshlaysiz?",
    chooseSubtitle: "Agar hisobingiz bo'lsa, oddiy kirish qiling. Yangi bo'lsangiz, Telegram orqali onboarding boshlanadi.",
    businessTitle: "Biznesingiz haqida qisqa ma'lumot",
    businessSubtitle: "Siz shu qismini to'ldirayotganingizda, OQIM chatlaringizdan o'rganishni boshlaydi.",
    businessName: "Biznes nomi",
    businessNamePlaceholder: "Masalan, OQIM Mobile",
    businessCategory: "Yo'nalish",
    businessRevenue: "Oylik tushum",
    offerSummary: "Nima sotasiz?",
    offerSummaryPlaceholder: "Masalan, ayollar kiyimi, sumka va aksessuarlar",
    region: "Qaysi hududda ishlaysiz?",
    regionPlaceholder: "Masalan, Toshkent",
    messageVolume: "Kuniga nechta mijoz yozadi?",
    replyTeamSize: "Kim javob beradi?",
    sellerTone: "Javob ohangi",
    agentMode: "OQIM qanday ishlasin?",
    sources: "Manbalar",
    sourcesHint: "Avval javob uchun kerakli ma’lumotlarni, keyin agent qanday ishlashini qo‘shing. OQIM natijani ko‘rsatadi va tasdiq so‘raydi.",
    brainDataTitle: "Javob ma’lumoti",
    brainDataHint: "Narx, xizmat, savol-javob, kompaniya, hujjat va kanal postlari. OQIM mijozga javob berishda shu ma’lumotga tayanadi.",
    agentDataTitle: "Agent qoidalari",
    agentDataHint: "Qachon so‘rash, qachon kutish, qanday ohangda yozish va nimani avtomatlashtirish.",
    sourceManualBadge: "Boshlash",
    sourceTypePicker: "Manba turini tanlash",
    sourcesPlaceholder: "Masalan: qaysi mahsulot/xizmat bor, kim uchun, narx qanday, yetkazish qanday ishlaydi",
    sourcesCount: (count: number) => `${count} ta manba`,
    websiteSource: "Sayt",
    websiteSourceHint: "Mahsulotlar, FAQ yoki xizmat sahifalarini o'qiydi.",
    websiteManyHint: "Bir nechta sayt yoki sahifa linkini alohida qatorga yozing.",
    websiteSourcePlaceholder: "https://sayt.uz\nhttps://sayt.uz/faq",
    telegramChannelSource: "Telegram kanal",
    telegramChannelSourceHint: "Kanal postlari, rasmlar va narxlarni o‘qiydi.",
    telegramChannelSourcePlaceholder: "@kanal_nomi\n@ikkinchi_kanal",
    telegramManyHint: "Bir nechta kanalni alohida qatorga yozing. Sana qo‘ysangiz OQIM faqat shu davrni o‘qiydi.",
    telegramDateFrom: "Qaysi sanadan",
    telegramDateTo: "Qaysi sanagacha",
    fileSource: "Fayl",
    fileSourceHint: "PDF, jadval, matn yoki rasm/screenshot yuboring.",
    voiceAudioSource: "Audio izoh",
    voiceAudioSourceHint: "Mikrofon yoki audio fayl avval tahrirlanadigan matnga aylanadi.",
    sellerMemorySource: "Qoida va ohang",
    sellerMemoryHint: "Agent qanday gapirsin, nimani so'rasin va qaysi holatda ehtiyot bo'lsin.",
    sellerMemoryReady: "qoida yoki agent matni yozildi",
    manualBrainSource: "Qo‘lda ma’lumot",
    manualBrainHint: "Hujjat bo‘lmasa ham biznes haqida muhim ma’lumotni shu yerga yozing.",
    ownerRulesHint: "Agent bajaradigan chegaralar: qachon savol bersin, qachon sizdan ruxsat so‘rasin.",
    addedSources: "Qo'shilgan manbalar",
    voiceSource: "Audio matni",
    voiceSourcePlaceholder: "Transkript shu yerga tushadi. Tahrirlab, agentga o‘qitiladigan matn sifatida qoldiring.",
    ownerRules: "Qoidalar",
    ownerRulesPlaceholder: "Masalan, yetkazib berish so'ralsa avval tuman va telefon so'ra",
    sourceReady: "Tayyor",
    sourceOptional: "Ixtiyoriy",
    fileReadFailed: "Faylni o'qib bo'lmadi. Kichikroq fayl yuboring.",
    businessContinue: "Davom etish",
    credentialsTitle: "OQIM kirishini sozlang",
    credentialsSubtitle: "Keyingi safar Telegramsiz ham telefon raqam va parol bilan kira olasiz.",
    passwordHint: "Kamida 8 ta belgi",
    learningNow: "OQIM hozir o‘rganmoqda",
    learningReady: "OQIM asosiy ma’lumotni yig‘ib bo‘ldi",
    learningWaiting: "Telegramdan tarix kutilyapti",
    learningHistoryReady: "Suhbatlar o'rganildi",
    learningHistoryReadyDesc: "Mijozlar tayyor. Ovoz uslubini keyin ham kuchaytirish mumkin.",
    learningDegraded: "O‘rganish to‘liq yakunlanmadi",
    learningDegradedDesc: "Suhbatlar ishlaydi. Ovoz yoki kontakt o'rganishni qayta urinish mumkin.",
    learningPercent: (n: number) => `${n}% tayyor`,
    learningContacts: (n: number) => `${n} ta oxirgi suhbat o‘rganishga olindi`,
    learningCustomers: (n: number, limit = 50) =>
      `Oxirgi ${limit} suhbat tekshirildi, ${n} tasi mijoz sifatida ajratildi`,
    learningHistoryWindow: (limit: number, messages: number) =>
      `OQIM faqat oxirgi ${limit} mijoz suhbatidan o‘rganadi. Har biridan ${messages} tagacha xabar olinadi; eski suhbatlar ro‘yxatda turadi, lekin boshlash paytida OQIMga berilmaydi.`,
    learningHistoryProcessed: (conversations: number, messages: number) =>
      `${conversations} suhbat o‘rganildi, ${messages} xabar mijoz bosqichlari va javob bilimlari uchun ishlatildi.`,
    learningVoice: "Ovoz profili tayyor",
    learningVoicePending: "Ovoz profili yaratilmoqda",
    learningVoiceDegraded: "Ovoz profili hozircha kuchsiz",
    learningPanelTitle: "OQIM nimalarni o‘rganyapti",
    learningPanelDesc: "Bu yerda suhbat tarixi, mijoz holati va yozish uslubi alohida ko‘rinadi.",
    historyBackfillTitle: "Suhbat tarixi",
    historyBackfillDetail: (contacts: number, customers: number, learningLimit = 50) =>
      contacts > 0 || customers > 0
        ? `${contacts} suhbat topildi, ${customers} mijoz ro‘yxatga olindi. Boshlashda oxirgi ${Math.min(Math.max(customers || contacts, 0), learningLimit)} mijoz suhbati o‘rganiladi.`
        : "Telegramdan eski suhbatlar o‘qilmoqda",
    autoCrmLearningTitle: "Mijoz bosqichlari",
    autoCrmLearningDetail: (customers: number) =>
      customers > 0
        ? `${customers} ta oxirgi mijoz bo‘yicha bosqich ajratilyapti: yangi, suhbat, kelishuv, to‘lov, yetkazish.`
        : "Mijoz bosqichlari suhbatlar o‘qilgandan keyin to‘ladi",
    voiceLearningTitle: "Yozish uslubi",
    voiceLearningFound: "Topilgan uslub belgilar",
    voiceLearningDetailReady: (count: number) =>
      count > 0 ? `${count} ta ohang belgisi topildi` : "Asosiy ohang tayyor",
    voiceLearningDetailPending: "Salomlashish, aniqlashtirish va savdoni yakunlash uslubingiz o‘rganilmoqda.",
    voiceLearningDetailWeak: "Yozish uslubi hali kuchsiz. Ko‘proq suhbat yoki audio qo‘shish mumkin.",
    retryLearning: "O‘rganishni qayta boshlash",
    learningRetryStarted: "O‘rganish qayta boshlandi",
    learningRetryFailed: "Qayta boshlash muvaffaqiyatsiz bo'ldi",
    finishSetup: "Sozlashni yakunlash",
    learnedReview: {
      title: "Topilgan ma’lumotlar",
      badge: "Tasdiqlash",
      products: "Mahsulotlar",
      knowledge: "Javoblar",
      rules: "Qoidalar",
      voice: "Uslub",
      integrations: "Integratsiya",
      factFallback: "Ma'lumot",
      needsReview: "Tekshirish kerak",
      edit: "Tahrirlash",
      correctText: "To'g'ri matn",
      saveEdit: "Tuzatib tasdiqlash",
      approve: "Tasdiqlash",
      reject: "Rad etish",
      summary: (products: number, answers: number, voice: number) =>
        `${products} ta mahsulot, ${answers} ta javob/qoidalar, ${voice} ta uslub`,
      more: (count: number) => `Yana ${count} ta bor`,
    },
    categories: {
      retail: "Savdo / do'kon",
      courses: "Kurslar",
      medicine: "Dorixona / tibbiyot",
      real_estate: "Ko'chmas mulk",
      services: "Xizmatlar",
      electronics: "Elektronika",
      fashion: "Kiyim va aksessuar",
      beauty: "Go'zallik",
      food: "Oziq-ovqat",
      other: "Boshqa",
    } as Record<string, string>,
    revenueBands: {
      under_10m: "10 mln so'mgacha",
      from_10m_to_50m: "10-50 mln so'm",
      from_50m_to_100m: "50-100 mln so'm",
      from_100m_to_300m: "100-300 mln so'm",
      above_300m: "300 mln+ so'm",
    } as Record<string, string>,
    messageVolumes: {
      "1_10": "1-10 mijoz",
      "10_50": "10-50 mijoz",
      "50_200": "50-200 mijoz",
      "200_plus": "200+ mijoz",
    } as Record<string, string>,
    replyTeams: {
      owner_only: "O'zim javob beraman",
      small_team: "Kichik jamoa",
      dedicated_manager: "Alohida operator",
    } as Record<string, string>,
    tones: {
      short_warm: "Qisqa va iliq",
      formal: "Rasmiy",
      friendly: "Do'stona",
    } as Record<string, string>,
    replyModes: {
      // Two states: off (agent does nothing) or autopilot (agent replies itself).
      // There is no draft/approve middle mode.
      draft: "O'chiq tursin, o'zim javob beraman",
      safe_autopilot: "O'zi javob bersin (avtopilot)",
    } as Record<string, string>,
  },

  // Agents
  agents: {
    title: "Agent",
    subtitle: "AI sotuvchi agentlarini sozlang",
    persona: "Shaxsiyat",
    trustMode: "Ishonch rejimi",
    tools: "Asboblar",
    voiceProfile: "Ovoz profili",
    defaultPersona: "Standart shaxsiyat",
    active: "Faol",
    inactive: "Nofaol",
    empty: "Agentlar yo'q",
    emptyDescription: "Sotuvchi agentingiz onboarding jarayonida sozlanadi",
    instructions: "Ko'rsatmalar",
    instructionsPlaceholder: "AI sotuvchiga qo'shimcha ko'rsatmalar...",
    autoSendThreshold: "Avto-yuborish chegarasi",
    escalationTopics: "Eskalatsiya mavzulari",
    setDefault: "Asosiy qilish",
    isDefault: "Asosiy agent",
    editAgent: "Agentni tahrirlash",
    noTools: "Asboblar sozlanmagan",
    create: {
      title: "Yangi agent",
      close: "Yopish",
      back: "Orqaga",
      next: "Davom etish",
      stepKindLabel: "Tur",
      stepKindTitle: "Agent turini tanlang",
      stepKindHint: "Agent qanday ish bajarishini tanlang. Keyin sozlamalar avtomatik to'ldiriladi.",
      stepBehaviorLabel: "Vazifa",
      stepBehaviorTitle: "Agent nima qiladi?",
      nameLabel: "Agent nomi",
      namePlaceholder: "Masalan, Sotuvchi agent",
      doesWhatLabel: "Nima qiladi?",
      doesWhatPlaceholder: "Masalan, mahsulot va narx savollariga javob beradi",
      whenRepliesLabel: "Qachon javob beradi?",
      whenRepliesPlaceholder: "Masalan, yangi xabar kelganda",
      neverDoesLabel: "Nimani qilmaydi?",
      neverDoesPlaceholder: "Masalan, narxni taxmin qilmaydi",
      stepReviewLabel: "Ko'rib chiqish",
      stepReviewTitle: "Ko'rib chiqish",
      agentMdHeading: "AGENT.md",
      agentMdEditable: "tahrirlash mumkin",
      behaviorGroupHeading: "Xulq-atvor",
      configGroupHeading: "Sozlama",
      autoSettingsHeading: "Avtomatik sozlamalar",
      permissionsRow: "Ruxsatlar",
      trustRow: "Ishonch",
      triggerRow: "Trigger",
      trustDraft: "Har safar tasdiq",
      trustAutopilot: "Avto-pilot (ishonchli bo'lsa)",
      triggerOnMessage: "Yangi xabar kelganda",
      triggerManual: "Faqat ega yoki BI buyrug'i bilan",
      submit: "Agent yaratish",
      drafting: "Agent tayyorlanmoqda…",
      draftError: "Agentni tayyorlab bo'lmadi. Qayta urinib ko'ring.",
      retry: "Qayta urinish",
      createError: "Agent yaratilmadi. Qayta urinib ko'ring.",
      created: "Agent yaratildi",
    },
    trustModes: {
      // Two trust states only: disabled (off) or autopilot (runs + sends).
      // Legacy keys map to "O'chirilgan" so old data renders honestly.
      disabled: "O'chirilgan",
      autopilot: "Avtopilot",
      draft: "O'chirilgan",
      autonomous: "O'chirilgan",
      manual: "O'chirilgan",
      green_auto: "Avtopilot",
      greenOnly: "Avtopilot",
      full_auto: "Avtopilot",
      full: "Avtopilot",
    } as Record<string, string>,
  },

  // Seller Agent reply inbox
  replies: {
    title: "Javoblar",
    empty: "Kutayotgan javoblar yo'q",
    emptyDescription: "Mijozlar yozganda sotuvchi agent javob taklif qiladi",
    search: "Javoblarni qidirish...",
    sendAll: "Hammasini yuborish",
    timeWaiting: "kutmoqda",
    open: "Ochish",
    pending: "ta javob kutmoqda",
    approveAllGreen: "Barchasini yuborish",
    sending: "Yuborilmoqda",
    customerMessage: "Mijoz",
    aiReply: "AI javob taklifi",
    openChat: "Chatga o'tish",
    selectReply: "Javobni tanlang",
    selectReplyHint: "To'liq suhbatni ko'rish uchun tanlang",
    source: "Manba",
    triggerLabel: {
      inbound_reply: "Kiruvchi xabar",
      follow_up: "Qayta aloqa",
    } as Record<string, string>,
    unknownTrigger: "Noma'lum trigger",
  },

  // Pipeline / Kanban
  pipeline: {
    title: "Savdo yo'li",
    empty: "Suhbatlar yo'q",
    emptyDescription: "Telegram ulangandan keyin suhbatlar bu yerda ko'rinadi",
    intelligenceTitle: "Mijozlar holati",
    intelligenceDescription: "OQIM suhbatlardan mijoz qayerda turgani, nima so‘ragani va qaysi javob kerakligini ajratadi.",
    latestFocus: "Ustuvor: oxirgi 50 mijoz. Eski suhbatlar saqlanadi, lekin tez javob uchun eng yangi mijozlar birinchi o‘rganiladi.",
    classifiedCount: (classified: number, total: number) => `${classified}/${total} suhbat joyiga qo‘yildi`,
    reviewCount: (count: number) => `${count} ta holatni ko‘rish kerak`,
    allNewLearning: "Hali dalil kam. OQIM suhbatlarni o‘qiyapti; to‘lov, kelishuv yoki yetkazish kabi bosqichlar aniq dalil topilganda chiqadi.",
    defaultedStage: "Hali ajratilmadi",
    lastIntent: (intent: string) => `Niyat: ${intent}`,
    urgent: "Tez javob kerak",
    stages: {
      new: "Yangi",
      qualified: "Suhbat",
      talking: "Suhbat",
      negotiation: "Kelishuv",
      negotiating: "Kelishuv",
      proposal: "Taklif",
      payment: "To'lov",
      delivery: "Yetkazish",
      waiting: "Kutilmoqda",
      won: "Buyurtma",
      lost: "Sovuq",
      cold: "Sovuq",
      manual_review: "Tekshirish",
    } as Record<string, string>,
    hasReply: "Javob taklifi bor",
    needsFollowup: "Javob kerak",
    stageBy: {
      ai: "OQIM ajratdi",
      llm: "OQIM ajratdi",
      system: "Tizim belgiladi",
      seller: "Siz belgiladingiz",
      crm_state: "Holatdan olindi",
      defaulted: "Dalil kam",
    } as Record<string, string>,
    moveToStage: "Bosqichni o'zgartirish",
    daysInStage: "kun",
    kanbanView: "Doska ko'rinishi",
    conversations: "ta suhbat",
  },

  // Settings
  settings: {
    title: "Sozlamalar",
    workspace: "Ish maydoni",
    workspaceName: "Ish maydoni nomi",
    workspaceNamePlaceholder: "Mening do'konim",
    telegram: "Telegram ulanishi",
    connected: "Ulangan",
    notConnected: "Ulanmagan",
    reconnecting: "Qayta ulanmoqda",
    degraded: "Cheklangan",
    failed: "Xatolik",
    connect: "Ulash",
    reconnect: "Qayta ulash",
    reconnectRequired: "Qayta ulash kerak",
    verify: "Tasdiqlash",
    disconnect: "Uzish",
    phoneNumber: "Telefon raqam",
    verificationCode: "Tasdiqlash kodi",
    telegramConnected: "Telegram hisobingiz ulangan.",
    instagram: "Instagram",
    instagramConnected: "Instagram biznes hisobingiz ulangan.",
    instagramNotConnected: "Instagramga ulanmagan",
    instagramConnect: "Instagramni ulash",
    instagramDisconnect: "Uzish",
    instagramReconnect: "Qayta ulash",
    instagramDescription:
      "Agent Instagram DM va izohlarga mijoz yozganidan keyin 24 soat ichida javob beradi.",
    instagramPilotHint:
      "Pilot davrida: Instagram hisobingiz OQIM ilovasiga tester sifatida qo'shilgan bo'lishi kerak. Taklifni Instagram ilovasida Sozlamalar > Veb-saytlar va ilovalar > Tester takliflari bo'limida qabul qilasiz.",
    instagramDisconnected: "Instagram uzildi.",
    instagramDisconnectError: "Instagramni uzishda xatolik.",
    instagramConnectError: "Instagramga ulanishda xatolik.",
    instagramConnectedToast: "Instagram muvaffaqiyatli ulandi.",
    instagramAlreadyConnected: "Bu Instagram hisobi boshqa ish maydoniga ulangan.",
    amocrm: "amoCRM",
    amocrmConnected: "amoCRM hisobingiz ulangan.",
    amocrmNotConnected: "amoCRM ga ulanmagan",
    amocrmConnect: "amoCRM ni ulash",
    amocrmDisconnect: "Uzish",
    amocrmReconnect: "Qayta ulash",
    amocrmDescription:
      "Agent har bir yangi mijozni amoCRM da lead sifatida ochadi va suhbat rivojiga qarab bosqichini yangilab boradi.",
    amocrmDisconnected: "amoCRM uzildi.",
    amocrmDisconnectError: "amoCRM ni uzishda xatolik.",
    amocrmConnectError: "amoCRM ga ulanishda xatolik.",
    amocrmConnectedToast: "amoCRM muvaffaqiyatli ulandi.",
    amocrmAlreadyConnected: "Bu amoCRM hisobi boshqa ish maydoniga ulangan.",
    ownerBotTitle: "Telegram boshqaruv boti",
    ownerBotDescription: "Biznes egasini Telegram orqali bog'lang.",
    ownerBotConnect: "Telegramni ulash",
    ownerBotConnected: "Ulangan",
    ownerBotNotProvisioned: "OQIM siz uchun Telegram boshqaruv botini avtomatik yaratadi.",
    ownerBotCreate: "Botni yaratish",
    ownerBotCreating: "Bot yaratilmoqda…",
    ownerBotNameLabel: "Bot nomi",
    ownerBotNamePlaceholder: "Masalan: Biznes boshqaruv",
    ownerBotUsernameLabel: "Bot foydalanuvchi nomi",
    ownerBotUsernamePlaceholder: "masalan: biznes_boshqaruv",
    ownerBotUsernameHint: "Bo'sh qoldirsangiz OQIM o'zi tanlaydi; kerak bo'lsa oxiriga \"_bot\" qo'shiladi.",
    ownerBotCreated: "Bot yaratildi.",
    ownerBotCreateError: "Botni yaratishda xatolik.",
    ownerBotDoNotForward: "Bu havola uni bosgan chatni bog'laydi — boshqalarga yubormang.",
    ownerBotOpenLink: "Havolani ochish",
    ownerBotUnbind: "Uzish",
    ownerBotUnbound: "Telegram uzildi.",
    ownerBotLinkError: "Havola yaratishda xatolik.",
    ownerBotUnbindError: "Uzishda xatolik.",
    integrations: "Integratsiyalar",
    comingSoon: "Tez kunda...",
    verifyError: "Tasdiqlash kodi noto'g'ri. Qayta urinib ko'ring.",
    connectError: "Ulanishda xatolik yuz berdi.",
    saving: "Saqlanmoqda...",
    telegramNotConnected: "Telegramga ulanmagan",
    telegramSessionExpired: "Telegram sessiyasi uzilgan yoki bekor qilingan. OQIM hisobingiz saqlanadi, faqat Telegramni qayta ulang.",
    telegramIdentityMismatch: "Bu workspace boshqa Telegram hisobiga ulangan. To'g'ri Telegram hisobingiz bilan qayta ulang.",
    telegramIdentityUnverified: "Telegram hisobini tekshira olmadik. Ishonch uchun qayta ulanish kerak.",
    telegramConnectionIssue: "Telegram ulanishida vaqtinchalik muammo bor. Qayta tekshirib ko'ring.",
    sellerAgentRuntime: "Sotuvchi agent navbati",
    sellerAgentRuntimeDesc: "AI javob tayyorlash holati va himoya limitlari",
    runtimeStatus: "Holat",
    runtimeRunning: "Ishlayapti",
    runtimePaused: "To'xtatilgan",
    runtimeCooldown: "Sovutilgan",
    runtimeBlocked: "Bloklangan",
    maxInflightReplies: "Bir vaqtdagi javoblar",
    maxReadyClaimsPerTick: "Har aylanishdagi olish limiti",
    liveQueue: "Jonli navbat",
    activeCandidates: "Faol",
    openCandidates: "Ochiq",
    readyCandidates: "Tayyor",
    leasedCandidates: "Band",
    generatingCandidates: "Yaratilmoqda",
    failedCandidates: "Xato",
    suppressedCandidates: "Bekor qilingan",
    completedCandidates: "Yakunlangan",
    consecutiveFailures: "Ketma-ket xatolar",
    cooldownUntil: "Cooldown gacha",
    lastSelectedAt: "Oxirgi tanlangan",
    lastCompletedAt: "Oxirgi yakunlangan",
    disabledReason: "To'xtatish sababi",
    pauseReplyGeneration: "Javob tayyorlashni to'xtatish",
    resumeReplyGeneration: "Javob tayyorlashni yoqish",
    clearCooldown: "Cooldownni tozalash",
    saveRuntime: "Limitlarni saqlash",
    runtimeDefaults: (inflight: number, claims: number) => `Standart: ${inflight} javob, ${claims} olish`,
    llmPolicy: "LLM model siyosati",
    llmPolicyDesc: "Har bir AI vazifasi qaysi Gemini modelidan foydalanishini boshqaring",
    llmPolicyCentralized: "Markazlashgan",
    llmOverride: "Override",
    llmCurrentModel: "Joriy model",
    llmUseDefault: (model: string) => `Standart: ${model}`,
  },

  // Common
  common: {
    appName: "OQIM",
    save: "Saqlash",
    cancel: "Bekor qilish",
    delete: "O'chirish",
    edit: "Tahrirlash",
    add: "Qo'shish",
    search: "Qidirish",
    loading: "Yuklanmoqda...",
    error: "Xatolik yuz berdi",
    errorOccurred: "Kutilmagan xatolik yuz berdi. Sahifani yangilang.",
    retry: "Qayta urinish",
    signOut: "Chiqish",
    more: "Boshqa",
    noResults: "Natija topilmadi",
    confirm: "Tasdiqlash",
    adding: "Qo'shilmoqda...",
    name: "Nomi",
    phone: "Telefon",
    type: "Turi",
    stage: "Bosqich",
    lastActive: "Oxirgi faollik",
    deleteConfirm: "O'chirishni tasdiqlaysizmi?",
    deleteConfirmDesc: "Bu amalni ortga qaytarib bo'lmaydi.",
    deleted: "O'chirildi",
    saved: "Saqlandi",
    added: "Qo'shildi",
    updated: "Yangilandi",
    created: "Yaratildi",
    sent: "Yuborildi",
    all: "Hammasi",
    close: "Yopish",
    back: "Orqaga",
    next: "Keyingi",
    comingSoon: "Tez kunda",
  },

  // Telegram embed
  telegram: {
    connectFirst: "Avval Telegramga ulaning",
    connectFirstDesc: "Xabarlarni ko'rish uchun Telegram hisobingizni ulang",
    sessionLoading: "Telegram sessiya yuklanmoqda...",
    loadError: "Xabarlarni yuklashda xatolik",
    retryLoad: "Qayta urinish",
  },

  // Time
  time: {
    now: "hozir",
    minutesAgo: "daq oldin",
    hoursAgo: "soat oldin",
    yesterday: "kecha",
    daysAgo: "kun oldin",
  },

  // CRM config
  crm: {
    title: "CRM",
    saved: "Saqlandi",
    saveError: "Saqlashda xatolik",
    connectPrompt: "Sozlash uchun CRM ulang",
    enablePipelineFirst: "Avval Voronkalar bo'limida kamida bitta voronkani yoqing",
    routingKeyRequired: "Yoqilgan har bir voronka uchun nom kiriting",
    mainPipelineBadge: "Asosiy",
    pipelinesTab: "Voronkalar",
    stagesTab: "Bosqichlar",
    routingInstructions: "Yo'naltirish ko'rsatmalari",
    useThisPipeline: "OQIM bu voronkadan foydalanadi",
    defaultPipeline: "Asosiy voronka",
    stageInstruction: "Ko'rsatma",
    routingKey: "Nomi",
    save: "Saqlash",
    selectPipeline: "Voronkani tanlang",
    unset: "Belgilanmagan",
    roles: {
      new: "Yangi",
      negotiation: "Kelishuv",
      qualified: "Malakali",
      won: "Yutildi",
      lost: "Yo'qotildi",
    },
  },

  // Autonomy / auto-send
  autonomy: {
    title: "Avtomatik javob",
    threshold: "Ishonch darajasi",
    thresholdDesc: (v: number) => `AI ${v}% dan yuqori ishonch bilan javob berganida avtomatik yuborish`,
    levels: { off: "O'chirilgan", cautious: "Ehtiyotkor", moderate: "O'rtacha", confident: "Ishonchli" },
    save: "Saqlash",
    saved: "Saqlandi",
    weeklyStats: (n: number) => `Bu hafta ${n} ta avtomatik javob yuborildi`,
    toast: (name: string) => `Avtomatik javob: ${name}`,
    sent: "Yuborildi",
    autoTab: "Avtomatik",
    todayCount: (n: number) => `Bugun avtomatik yuborilgan: ${n}`,
    onboardingExplain: "AI 70% dan yuqori ishonch bilan javoblarni avtomatik yuboradi.",
    configureLater: "Keyinroq sozlash mumkin",
  },
} as const
